# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.2
_src_path: https://github.com/akretion/akretion-addons-repo-template.git
black_version: 20.8b1
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: '14.0'
prettify_xml: true
python_line_length: 88
rebel_module_groups: []
repo_description: The modules present in this repo should go to OCA on the long run,
  they are still not used a lot and still need to prove themselves
repo_name: Generic Odoo module in incubation
repo_slug: ak-odoo-incubator
travis_apt_packages: []
travis_apt_sources: yml
