language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0"
  # - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"  # from oca/server-tools

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  # - TESTS="1" ODOO_REPO="OCA/OCB" MAKEPOT="1"  # from oca/server-tools

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone https://github.com/akretion/akretion-quality-tools ${HOME}/akretion-quality-tools
  - export PATH=${HOME}/akretion-quality-tools/travis:${PATH}
  - travis_configure

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
