language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="10.0" TESTS="1" LINT_CHECK="0"

  matrix:
  - TESTS="0" LINT_CHECK="1"
  - ODOO_REPO="odoo/odoo" EXCLUDE="product_categ_available_pos"
  - ODOO_REPO="OCA/OCB" EXCLUDE="product_categ_available_pos"
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo" EXCLUDE="product_categ_available_pos"
  - UNIT_TEST="1" ODOO_REPO="OCA/OCB" EXCLUDE="product_categ_available_pos"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - git clone https://github.com/akretion/akretion-quality-tools ${HOME}/akretion-quality-tools
  - export PATH=${HOME}/akretion-quality-tools/travis:${PATH}
  - travis_configure

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

