from . import purchase_requisition_information_mixin
from . import purchase_order
from . import sale_order
from . import purchase_requisition
from . import purchase_requisition_line
from . import purchase_requisition_proposal
from . import purchase_requisition_type
from . import res_company
from . import ir_config
