# -*- coding: utf-8 -*-
from odoo import fields, models


class Agreement(models.Model):
    _inherit = 'agreement'

    holding_company_id = fields.Many2one(
        comodel_name='res.company', string='Holding Company',
        help=u"Select the holding company used to invoice")
    holding_discount = fields.Float(
        string=u'% Holding Discount',
        help=u"")
    holding_invoice_generated_by = fields.Selection([
        ('holding', 'Holding'),
        ('child', 'Child'),
    ], default='holding',
        string=u'Invoice Generated by',
        help=u"If the holding invoice is generated by a user of the holding "
             u"company you have to select the option holding. If it's the "
             u"child company you have to select the child option")
    holding_invoice_group_by = fields.Selection([
        ('none', 'None'),
        ('sale', 'Sale'),
    ], default='none',
        string=u'Invoice Group by',
        help=u"This will define how the sales are grouped on the invoice")
    holding_product_id = fields.Many2one(
        comodel_name='product.product',
        string=u'Holding Invoice Product',
        help=u"This product will be used for the sales line in the Holding "
             u"Invoice. Accounting information will be taken on this product")
    holding_royalty_product_id = fields.Many2one(
        comodel_name='product.product',
        string=u'Royalty Holding Product',
        help=u"This product will be used for the royalty line in the Holding "
             u"Invoice. Accounting information will be taken on this product")
    journal_id = fields.Many2one(
        comodel_name='account.journal', string=u'Journal',
        company_dependent=True)
