-
  Sale config
-
  !python {model: sale.config.settings, id: False}: |
    config = self.create({})
    if not config.group_multi_salesteams:
        config.write({'group_multi_salesteams': True})
        config.execute()
