# Copyright 2025 Akretion (http://www.akretion.com).
# @author Florian Mounier <florian.mounier@akretion.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
# flake8: noqa


def create(title: str, iid=3, pid=1) -> dict:
    return {
        "object_kind": "merge_request",
        "event_type": "merge_request",
        "user": {
            "id": 1,
            "name": "Administrator",
            "username": "root",
            "avatar_url": "https://www.gravatar.com/avatar/5d2c9a25d06cacddd79de18e13c78ee9a771359bed9d12131c74042e6ba661bd?s=80&d=identicon",
            "email": "[REDACTED]",
        },
        "project": {
            "id": pid,
            "name": "Test project",
            "description": None,
            "web_url": "http://localhost:8929/root/test-project",
            "avatar_url": None,
            "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "git_http_url": "http://localhost:8929/root/test-project.git",
            "namespace": "Administrator",
            "visibility_level": 0,
            "path_with_namespace": "root/test-project",
            "default_branch": "main",
            "ci_config_path": None,
            "homepage": "http://localhost:8929/root/test-project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "http_url": "http://localhost:8929/root/test-project.git",
        },
        "object_attributes": {
            "assignee_id": None,
            "author_id": 1,
            "created_at": "2025-10-21 13:39:15 UTC",
            "description": "Tests the hooks",
            "draft": False,
            "head_pipeline_id": None,
            "id": 35,
            "iid": iid,
            "last_edited_at": None,
            "last_edited_by_id": None,
            "merge_commit_sha": None,
            "merge_error": None,
            "merge_params": {"force_remove_source_branch": "1"},
            "merge_status": "checking",
            "merge_user_id": None,
            "merge_when_pipeline_succeeds": False,
            "milestone_id": None,
            "source_branch": "TestBranch",
            "source_project_id": 1,
            "state_id": 1,
            "target_branch": "main",
            "target_project_id": 1,
            "time_estimate": 0,
            "title": title,
            "updated_at": "2025-10-21 13:39:16 UTC",
            "updated_by_id": None,
            "prepared_at": "2025-10-21 13:39:16 UTC",
            "assignee_ids": [],
            "blocking_discussions_resolved": True,
            "detailed_merge_status": "checking",
            "first_contribution": True,
            "human_time_change": None,
            "human_time_estimate": None,
            "human_total_time_spent": None,
            "labels": [],
            "last_commit": {
                "id": "201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "message": "Edit README.md",
                "title": "Edit README.md",
                "timestamp": "2025-10-21T13:20:56+00:00",
                "url": "http://localhost:8929/root/test-project/-/commit/201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "author": {
                    "name": "Administrator",
                    "email": "gitlab_admin_a8f055@example.com",
                },
            },
            "reviewer_ids": [],
            "source": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "state": "opened",
            "system": False,
            "target": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "time_change": 0,
            "total_time_spent": 0,
            "url": "http://localhost:8929/root/test-project/-/merge_requests/3",
            "work_in_progress": False,
            "approval_rules": [],
            "action": "open",
        },
        "labels": [],
        "changes": {
            "merge_status": {"previous": "preparing", "current": "checking"},
            "updated_at": {
                "previous": "2025-10-21 13:39:15 UTC",
                "current": "2025-10-21 13:39:16 UTC",
            },
            "prepared_at": {"previous": None, "current": "2025-10-21 13:39:16 UTC"},
        },
        "repository": {
            "name": "Test project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "description": None,
            "homepage": "http://localhost:8929/root/test-project",
        },
    }


def update(title: str, iid=3, pid=1, old_title="") -> dict:
    return {
        "object_kind": "merge_request",
        "event_type": "merge_request",
        "user": {
            "id": 1,
            "name": "Administrator",
            "username": "root",
            "avatar_url": "https://www.gravatar.com/avatar/5d2c9a25d06cacddd79de18e13c78ee9a771359bed9d12131c74042e6ba661bd?s=80&d=identicon",
            "email": "[REDACTED]",
        },
        "project": {
            "id": pid,
            "name": "Test project",
            "description": None,
            "web_url": "http://localhost:8929/root/test-project",
            "avatar_url": None,
            "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "git_http_url": "http://localhost:8929/root/test-project.git",
            "namespace": "Administrator",
            "visibility_level": 0,
            "path_with_namespace": "root/test-project",
            "default_branch": "main",
            "ci_config_path": None,
            "homepage": "http://localhost:8929/root/test-project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "http_url": "http://localhost:8929/root/test-project.git",
        },
        "object_attributes": {
            "assignee_id": None,
            "author_id": 1,
            "created_at": "2025-10-21 13:39:15 UTC",
            "description": "Tests the update hooks",
            "draft": False,
            "head_pipeline_id": None,
            "id": 35,
            "iid": iid,
            "last_edited_at": "2025-10-21 13:40:24 UTC",
            "last_edited_by_id": 1,
            "merge_commit_sha": None,
            "merge_error": None,
            "merge_params": {"force_remove_source_branch": "1"},
            "merge_status": "can_be_merged",
            "merge_user_id": None,
            "merge_when_pipeline_succeeds": False,
            "milestone_id": None,
            "source_branch": "TestBranch",
            "source_project_id": 1,
            "state_id": 1,
            "target_branch": "main",
            "target_project_id": 1,
            "time_estimate": 0,
            "title": title,
            "updated_at": "2025-10-21 13:40:24 UTC",
            "updated_by_id": 1,
            "prepared_at": "2025-10-21 13:39:16 UTC",
            "assignee_ids": [],
            "blocking_discussions_resolved": True,
            "detailed_merge_status": "mergeable",
            "first_contribution": True,
            "human_time_change": None,
            "human_time_estimate": None,
            "human_total_time_spent": None,
            "labels": [],
            "last_commit": {
                "id": "201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "message": "Edit README.md",
                "title": "Edit README.md",
                "timestamp": "2025-10-21T13:20:56+00:00",
                "url": "http://localhost:8929/root/test-project/-/commit/201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "author": {
                    "name": "Administrator",
                    "email": "gitlab_admin_a8f055@example.com",
                },
            },
            "reviewer_ids": [],
            "source": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "state": "opened",
            "system": False,
            "target": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "time_change": 0,
            "total_time_spent": 0,
            "url": "http://localhost:8929/root/test-project/-/merge_requests/3",
            "work_in_progress": False,
            "approval_rules": [],
            "action": "update",
        },
        "labels": [],
        "changes": {
            "description": {
                "previous": "Tests the hooks",
                "current": "Tests the update hooks",
            },
            "last_edited_at": {"previous": None, "current": "2025-10-21 13:40:24 UTC"},
            "last_edited_by_id": {"previous": None, "current": 1},
            "title": {
                "previous": old_title,
                "current": title,
            },
            "updated_at": {
                "previous": "2025-10-21 13:39:16 UTC",
                "current": "2025-10-21 13:40:24 UTC",
            },
            "updated_by_id": {"previous": None, "current": 1},
        },
        "repository": {
            "name": "Test project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "description": None,
            "homepage": "http://localhost:8929/root/test-project",
        },
    }


def close(title: str, pid=1, iid=3) -> dict:
    return {
        "object_kind": "merge_request",
        "event_type": "merge_request",
        "user": {
            "id": 1,
            "name": "Administrator",
            "username": "root",
            "avatar_url": "https://www.gravatar.com/avatar/5d2c9a25d06cacddd79de18e13c78ee9a771359bed9d12131c74042e6ba661bd?s=80&d=identicon",
            "email": "[REDACTED]",
        },
        "project": {
            "id": pid,
            "name": "Test project",
            "description": None,
            "web_url": "http://localhost:8929/root/test-project",
            "avatar_url": None,
            "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "git_http_url": "http://localhost:8929/root/test-project.git",
            "namespace": "Administrator",
            "visibility_level": 0,
            "path_with_namespace": "root/test-project",
            "default_branch": "main",
            "ci_config_path": None,
            "homepage": "http://localhost:8929/root/test-project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
            "http_url": "http://localhost:8929/root/test-project.git",
        },
        "object_attributes": {
            "assignee_id": None,
            "author_id": 1,
            "created_at": "2025-10-21 13:39:15 UTC",
            "description": "Tests the update hooks",
            "draft": False,
            "head_pipeline_id": None,
            "id": 35,
            "iid": iid,
            "last_edited_at": "2025-10-21 13:40:24 UTC",
            "last_edited_by_id": 1,
            "merge_commit_sha": None,
            "merge_error": None,
            "merge_params": {"force_remove_source_branch": "1"},
            "merge_status": "can_be_merged",
            "merge_user_id": None,
            "merge_when_pipeline_succeeds": False,
            "milestone_id": None,
            "source_branch": "TestBranch",
            "source_project_id": 1,
            "state_id": 2,
            "target_branch": "main",
            "target_project_id": 1,
            "time_estimate": 0,
            "title": title,
            "updated_at": "2025-10-21 13:41:57 UTC",
            "updated_by_id": 1,
            "prepared_at": "2025-10-21 13:39:16 UTC",
            "assignee_ids": [],
            "blocking_discussions_resolved": True,
            "detailed_merge_status": "not_open",
            "first_contribution": True,
            "human_time_change": None,
            "human_time_estimate": None,
            "human_total_time_spent": None,
            "labels": [],
            "last_commit": {
                "id": "201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "message": "Edit README.md",
                "title": "Edit README.md",
                "timestamp": "2025-10-21T13:20:56+00:00",
                "url": "http://localhost:8929/root/test-project/-/commit/201e7022d23f6e6212adf66514f3e65b89b3c8e5",
                "author": {
                    "name": "Administrator",
                    "email": "gitlab_admin_a8f055@example.com",
                },
            },
            "reviewer_ids": [],
            "source": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "state": "closed",
            "system": False,
            "target": {
                "id": 1,
                "name": "Test project",
                "description": None,
                "web_url": "http://localhost:8929/root/test-project",
                "avatar_url": None,
                "git_ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "git_http_url": "http://localhost:8929/root/test-project.git",
                "namespace": "Administrator",
                "visibility_level": 0,
                "path_with_namespace": "root/test-project",
                "default_branch": "main",
                "ci_config_path": None,
                "homepage": "http://localhost:8929/root/test-project",
                "url": "ssh://git@localhost:2424/root/test-project.git",
                "ssh_url": "ssh://git@localhost:2424/root/test-project.git",
                "http_url": "http://localhost:8929/root/test-project.git",
            },
            "time_change": 0,
            "total_time_spent": 0,
            "url": "http://localhost:8929/root/test-project/-/merge_requests/3",
            "work_in_progress": False,
            "approval_rules": [],
            "action": "close",
        },
        "labels": [],
        "changes": {
            "state_id": {"previous": 1, "current": 2},
            "updated_at": {
                "previous": "2025-10-21 13:40:24 UTC",
                "current": "2025-10-21 13:41:57 UTC",
            },
        },
        "repository": {
            "name": "Test project",
            "url": "ssh://git@localhost:2424/root/test-project.git",
            "description": None,
            "homepage": "http://localhost:8929/root/test-project",
        },
    }
